### ISSUE TITLE
Add OrientDB Support

### ISSUE THREAD

**Issue by Jotschi** [bayofmany/peapod#10]
I tried to use peapod in combination with the TP3 layer which michael pollmeier wrote:

```
        <dependency>
            <groupId>com.michaelpollmeier</groupId>
            <artifactId>orientdb-gremlin</artifactId>
            <version>3.1.1-incubating.1</version>
        </dependency>
```

I added the following test case:

```
public class OrientDBSuite extends GraphTestSuite {

	public static final String URL = "memory:" + OrientDBSuite.class.getSimpleName();

	@ClassRule
	public static TemporaryFolder folder = new TemporaryFolder();

	@BeforeClass
	public static void setGraphProvider() throws IOException {
		GraphTest.graphProvider = new GraphProvider() {
			public Graph getGraph() throws IOException {
				return new OrientGraphFactory(URL + folder.newFolder().getAbsolutePath(), "root", "root").getNoTx();
			}
		};
	}

}
```

So far 4 tests are failing. OrientDB only supports Strings or OrientID objects for Ids. In some cases Peapod is using Class objects.

**Comment by Jotschi** [comment]
I got it down to two test failing - #11

**Comment by Jotschi** [comment]
Maybe the TP Implementation does not support VertexProperty.Cardinality.list properties and thus the remaining two tests are failing.
@velo @mpollmeier Do you perhaps know whether orientdb-gremlin supports those properties?

**Comment by Jotschi** [comment]
Got it.. OrientDB does not "supportsMultiProperties" - The VertexPropertyTest is therefore not working as expected since only the last location property is stored in the vertex.

**Comment by velo** [comment]
So, we are good?

**Comment by Jotschi** [comment]
@velo Yes, i guess so. All tests are passing.

**Comment by wsalembi** [comment]
Your pull request was accepted. Thanks for your contribution.
