### ISSUE TITLE
Why annotate methods instead of fields and why abstract?

### ISSUE THREAD

**Issue by Isabaellchen** [bayofmany/peapod#13]
Hey there, one thing i do not understand about peapod is why you chose to annotate methods with @In,@Out or @Property instead of fields. Also why do my annotated classes need to be abstract? I find this pretty confusing as i am coming from dependency injection frameworks, where youd inject foreing DomainModel objects as fields and the framework generates the add/remove/get functions for you, regardless of their positioning and regardless of abstract or not. But there probably is a reason to this, so maybe youd like to share.

**Comment by wsalembi** [comment]
Hi Isabaellchen. 

Classic ORM libraries copy the data from a datasource to the model class, edit the copied data and resynchronize to the datasource before commit time. 
In contrast, Peapod does not copy the data but instead encapsulates a Tinkerpop vertex and dispatches each event on the model class to the Tinkerpop vertex. You declare the required methods (either within an interface or abstract class), annotate them and Peapod will generate the implementation for these methods. 

Have a look at the code Peapod generates. It'll become much clearer.

Best regards
