### ISSUE TITLE
Object Inheritance and Querying

### ISSUE THREAD

**Issue by bradsdavis** [bayofmany/peapod#6]
We ran into this with Frames a while ago -- I believe the object inheritance structure should be taken into account when querying for objects.  So take the example:

ClassB extends ClassA

When you query for ClassA, you should get all objects ClassA & ClassB.  There are two ways to handle this, I assume; the first is to modify Peapod to make the Label of class type contain both ClassA and ClassB.  Alternatively, and I think this is the better solution: determine at run time the object structure of all @Vertex objects, and store that in a cache.  At query time, query for all types extended or implemented by the given type. I think this is a better solution because if you change the object structure and redeploy, the graph will stay consistent.

**Comment by wsalembi** [comment]
Hi Brad, the behavior you describe is already implemented. At runtime a list of labels is constructed for each base class that has subclasses. Look at the test `peapod.inheritance.InheritanceTest`. 

Did you find any bug related to this in your project?
