### ISSUE TITLE
Impl is not abstract and does not override abstract method start() in peapod.FramedVertexTraversal

### ISSUE THREAD

**Issue by Isabaellchen** [bayofmany/peapod#8]
I was not able to use the peapod tag on stackoverflow, so im just linking it here.

http://stackoverflow.com/questions/35972962/peapod-impl-is-not-abstract-and-does-not-override-abstract-method-start-in-pe

**Comment by wsalembi** [comment]
I think it is just an issue of not compiling with Java 8. Try to add this to your pom.xml file

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.3</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                    <compilerArgument>-proc:none</compilerArgument>
                </configuration>
            </plugin>
        </plugins>
    </build>

**Comment by Isabaellchen** [comment]
Thanks that did the trick. Had to fix some version issues afterwards but its all working now.
