### ISSUE TITLE
No framer found for TinkerVertex with label vertex

### ISSUE THREAD

**Issue by tsohil** [bayofmany/peapod#9]
I am getting this runtime exception "No framer found for TinkerVertex with label vertex" while running my demo app.

I have already checked your solution to similar [issue](https://github.com/bayofmany/peapod/issues/2). I followed your [comment](https://github.com/bayofmany/peapod/issues/2#issuecomment-116266875) providing steps to setup automatic annotation processing, but no luck.

Here is my console out

```
java.lang.RuntimeException: No framer found for TinkerVertex with label vertex
	at peapod.internal.runtime.FramerRegistry.get(FramerRegistry.java:97)
	at peapod.FramedGraph.frame(FramedGraph.java:142)
	at peapod.FramedGraph.v(FramedGraph.java:133)
	at tinkerpopSample.App.main(App.java:20)
```

**Comment by wsalembi** [comment]
Can you see any generated classes in your project? Which JDK and maven version do you use?

**Comment by tsohil** [comment]
No, there are no generated classes. I am running JDK1.8, Maven-3.3.3 in Eclipse Mars.

**Comment by wsalembi** [comment]
Can you send me the demo project. I'll have a look at your source code

**Comment by Jotschi** [comment]
@tsohil You may need to install m2e-apt in order to process the annotations within eclipse.

* Install m2e-apt
* Window -> Preferences -> Maven -> Annotation Processing: Select "Automatically configure JDT APT"
* Update the maven project

**Comment by Jotschi** [comment]
@tsohil Sorry, I just noticed that I missed the fact that the peapod project is currently not setup to be compatible with Eclipse. Unfortunately Maven and Eclipse can be a bit tricky. The pom.xml of the core submodule has to be changed slightly. 

You also need to install the build-helper-maven-plugin using the eclipse marketplace.

https://github.com/Jotschi/peapod/commit/1cab872f2677c7d3e15f68f6f4f7c4887a38acc3

**Comment by tsohil** [comment]
@Jotschi I got this update bit late but still thanks a lot.

**Comment by joeyfezster** [comment]
after doing this, all my generated methods in all my generated classes showed this error:
The method <doSomething()> of type <someType> should be tagged with @Override since it actually overrides a superclass method.

i can manually add the tag, but this is autogenerated code.. how can i stop this?
i also get "unnecessary semicolon" error in a couple of places
